### ISSUE TITLE
Test superadmin features

### ISSUE THREAD

**Issue by ksmontville** [yeatmanlab/roar-dashboard#869]
" - Check the Test Administrations
 - Test the Search Administration feature
 - Enroll Users
 - Create and Administration"

**Comment by richford** [comment]
I also noticed that if one returns to administrator home from another route, the administration list is empty.

### To reproduce,
1. Log in as an administrator (e.g. demo-district-admin with password: "password") or super-administrator.
2. Allow the administration list to load completely
3. Navigate to another route (e.g. list-orgs or create-administration)
4. Return to the administrator home (either by clicking on the ROAR logo or on the Administrations > View Administrations menu item).

### Expected behavior:

Page displays the same administrations seen in step 2.

### Actual behavior:

![Image](https://github.com/user-attachments/assets/a0f4bfda-793a-4615-b5ef-49461413641f)

**Comment by maximilianoertel** [comment]
@ksmontville / @richford is this a known issue that can be reproduced on another PR environment? As mentioned above, this does indeed seem to be a CORS issue and hence unlikely to be introduced/caused by the work on the query composables

**Comment by ksmontville** [comment]
This bug persists even when running this PR on `localhost:5173`. Attempting to register new students throws a CORS error.

![Image](https://github.com/user-attachments/assets/94839f91-9c66-4c89-b57a-94a83217c226)

**Comment by ksmontville** [comment]
Steps to reproduce:

1. Sign in as a super admin
2. Navigate to register students page
3. Upload a valid .csv with test data
4. Select correct column headers
5. Click to register
